version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/node:16.15.0"
      - image: "cimg/redis:6.2.6"
      - image: "cimg/mysql:5.7.36"  
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
      
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: |
          sudo apt-get install default-mysql-client
          mysql -h 127.0.0.1 -u root -e "create database test_db"
          mysql -h 127.0.0.1 -u root test_db < employee.sql
      - run: |
          npm install
          npm start&
          export API_PID=$!
      # - run: |
      #     npm test
      #     make smoke
      #     kill $API_PID

workflows:
  elastic-beanstalk-workflow:
    jobs:
      - build
      - eb/deploy:
          context: aws-creds
          environment-name: ebtest-env
          application-name: eb-test
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
